version: '3'

services:
  localstack-for-scheduler:
    image: localstack/localstack:0.12.0
    ports:
      - "5566:4566"
      - "8000:8000"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_data:/tmp/localstack/data

  dynamodb-admin-for-scheduler:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack-for-scheduler

volumes:
  localstack_data:
