version: '3'

services:
  scheduler-1:
    build: .
    depends_on:
      - localstack-for-scheduler

  localstack-for-scheduler:
    image: localstack/localstack:0.12.0
    ports:
      - "4566:4566"
      - "8000:8000"
    environment:
      - SERVICES=dynamodb
#      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=non_empty_key
      - AWS_SECRET_ACCESS_KEY=non_empty_key
    volumes:
      - localstack_data:/tmp/localstack/data

  dynamodb-admin-for-scheduler:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack-for-scheduler:4566
    depends_on:
      - localstack-for-scheduler

volumes:
  localstack_data:
