package com.mukit.springbootscheduler.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Id;

@Data
@DynamoDBTable(tableName = "student")
public class Student {

    @Id
    @DynamoDBHashKey(attributeName = "studentId")
    private String studentId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "age")
    private int age;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBIndexHashKey(attributeName = "status", globalSecondaryIndexName = "status-index")
    private String status;

    @DynamoDBIndexRangeKey(attributeName = "createdDate", globalSecondaryIndexNames = "status-index")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Long createdDate;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private String lastModifiedDate;

}
